### ISSUE TITLE
Make app runnable without API key

### ISSUE THREAD

**Issue by bstrauch24** [HackIllinois/android#129]
When this project is cloned in Android Studio, it's not immediately runnable because it's missing the `GOOGLE_MAPS_API_KEY`. You should be able to run the app, but maps should break. I'm not sure if this is possible, but this would make it easier for people outside of HackIllinois (or people interested in joining Android at the start of the year) to contribute.

**Comment by patrickfeltes** [comment]
Definitely agree. There should be a way to do this

**Comment by PradyumnaShome** [comment]
How about using the blob store to dynamically inject the API key at runtime?
