### ISSUE TITLE
Integrate Travis CI to automate release process

### ISSUE THREAD

**Issue by patrickfeltes** [HackIllinois/android#138]

**Comment by bstrauch24** [comment]
Let me know when you've set up an alpha release in the play store

**Comment by faogustavo** [comment]
Why don't you use [Bitrise](https://blog.bitrise.io/free-developer-plan-features-for-open-source-projects-on-bitrise)? It has a free plan for open source projects.

**Comment by patrickfeltes** [comment]
@faogustavo Thanks for the suggestion, I'll look into it!

**Comment by patrickfeltes** [comment]
https://gist.github.com/maskaravivek/517a542e20a092a3e2f638228faa3744
