### ISSUE TITLE
Use the user’s registration data on the profile page

### ISSUE THREAD

**Issue by patrickfeltes** [HackIllinois/android#153]
We are currently using the User object, which is not dependable for names.

- [ ] Update `Attendee.kt` to provide a method `getFullName()`. Look at `User.kt` for an example.
- [ ] Update `ProfileFragment.kt`'s `updateAttendeeInformation()` and `updateUserInformation()` to set the name in the UI from the Attendee object. If the attendee object is null, fallback to using the User object.

**Comment by faogustavo** [comment]
@patrickfeltes do you have some example/mock of how you expect the UI to be?
