### ISSUE TITLE
The room schemas directory is not being provided

### ISSUE THREAD

**Issue by faogustavo** [HackIllinois/android#159]
When the app is building, the room tries to export the JSON with the Room schema. This need to be set on the Gradle file.
This is not a bug, just build warning.

![image](https://user-images.githubusercontent.com/7588480/65279874-90131580-db05-11e9-8ccd-48fefec38173.png)

I'm working on this one, just open a PR to map it.

**Comment by patrickfeltes** [comment]
Awesome! If you can push up the schema generated as well, that would be fantastic! It would be good to have a history so that we can add migrations as needed.

**Comment by faogustavo** [comment]
@patrickfeltes the current version of room is 7. Can I downgrade back to 1 or we just create the history from this version?

**Comment by patrickfeltes** [comment]
I think downgrading to 1 should be fine since we will be releasing under a new package name in the Play Store, so no one will have a database already.
