### ISSUE TITLE
Star gets squished on event info page

### ISSUE THREAD

**Issue by patrickfeltes** [HackIllinois/android#245]
This is probably the same on project info page

**Comment by patrickfeltes** [comment]
I think we might be able to fix this by constraining the right side of the title text view to the star and then making the title text view width 0dp. This makes it fill the space provided and then wrap the text if it goes too far.

**Comment by RaghavSaini01** [comment]
Yeah that's kind of what I was thinking too, because it seemed like the star would get kind of pushed with the current constraint if the text was too large. I'll change that and try it out.
