### ISSUE TITLE
Event times, not as per the timezone.

### ISSUE THREAD

**Issue by rushatgabhane** [HackIllinois/android#351]
![Screenshot_20210410-115017~2](https://user-images.githubusercontent.com/29673073/114264697-0da6bb00-99f5-11eb-8a40-dcd9ba4d056a.png)

**Comment by timot3** [comment]
Hey, I'm not quite sure what you mean. Can you please clarify what the issue is here?

**Comment by rushatgabhane** [comment]
> Hey, I'm not quite sure what you mean. Can you please clarify what the issue is here?

Let's say an event is at 3 PM CDT ( UTC -5 ).
But I live in France ( UTC +2 ). 

Time difference is 7 hours.

So, I expect the event time in Android app to be 10 PM local time (France).
Instead it just shows 3 PM.
