### ISSUE TITLE
Outdoor Maps Location Updates

### ISSUE THREAD

**Issue by bstrauch24** [HackIllinois/android#95]
The outdoor maps fragment asks users for permission to use location, but it does not successfully populate the page with time & distance info on some phones. The walking icon is displayed, but there is nothing to the right of it.

**Comment by patrickfeltes** [comment]
We should switch to using this: https://developer.android.com/training/location/receive-location-updates

Seems like Google recommends this over using just the base android location API. We already have google play services, so this shouldn't be an issue.

**Comment by bstrauch24** [comment]
Alright, I'm going to leave this issue here for the future. It actually works 100% of the time, it's just really slow sometimes (takes 10-15 seconds for the data to appear)

**Comment by bstrauch24** [comment]
Just kidding, it is actually an issue.
