### ISSUE TITLE
Indoor Maps Zoom

### ISSUE THREAD

**Issue by bstrauch24** [HackIllinois/android#98]
Zoom into indoor maps images
https://medium.com/quick-code/pinch-to-zoom-with-multi-touch-gestures-in-android-d6392e4bf52d

**Comment by patrickfeltes** [comment]
It looks like the high resolution of the images is causing some performance issues with zooming and panning. I have tried to use [this library](https://github.com/davemorrissey/subsampling-scale-image-view), which works well on newer devices (S8) but not so well on a Nexus 5X.

**Comment by bstrauch24** [comment]
Should be doable now since images have variable resolution
